description: Single query baseline
environment:
  image: pytorch/pytorch:1.7.1-cuda11.0-cudnn8-devel
  setup:
    - pip install -r requirements.txt --user

code:
  local_dir: $CONFIG_DIR/..

# use amlt ti to view these
# target:
#   service: amlk8s
#   name: itphyperdgx2cl1
#   # vc: hai3
#   vc: hai2

# these have only 8 gpus
target:
  service: amlk8s
  name: itplabrr1cl1
  # vc: hai3
  vc: resrchvc

storage:
  output:
    storage_account_name: chansingh
    container_name: cs1
    mount_dir: /mnt/output # dir on the local machine

jobs:
- name: single_query
  sku: G8
  command:
  - python scripts/submit_single_query_baseline.py --dummy