description: Sweep autoprompting
environment:
  image: pytorch/pytorch:1.7.1-cuda11.0-cudnn8-devel
  setup:
    - pip install -r requirements.txt --user

code:
  local_dir: $CONFIG_DIR/../..

target:
  service: amlk8s
  # run "amlt target list amlk8s" to list the names of available AMLK8s targets
  name: itphyperdgx2cl1
  vc: hai3

storage:
  output:
    storage_account_name: chansingh
    container_name: cs1
    mount_dir: /mnt/output # dir on the local machine

jobs:
- name: sweep_suffixes
  sku: G16
  command:
  - python scripts/submit_sweep.py /mnt/output/sweep_midnight2